import type { Metadata } from "next";
import { Geist, Geist_Mono, BBH_Sans_Bartle, Bebas_Neue  } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bbhSansBartle = BBH_Sans_Bartle({
  variable: "--font-bbh-sans-bartle",
  subsets: ["latin"],
  weight: ['400'],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${bbhSansBartle.variable} ${bebasNeue.variable} scroll-smooth`}>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
